Implemented get_firewall_policies
napalm-automation/napalm-fortios pull request #22
Opened 2016-11-17 13:22 UTC by awlx

I implemented a new method to get all defined IPv4 Firewall Policies on a Fortigate. 

I hope this PR complies with the guidelines.

2016-11-20 13:51 UTC, dbarrosop commented
Relates to napalm-automation/napalm-base#136

2016-11-24 07:43 UTC, dbarrosop commented on napalm_fortios/fortios.py
> +            default_policy[policy[key]['srcintf'] + '-to-'  + policy[key]['dstintf']] = dict()
it's gonna be cleaner if you do

```
my_key = "{}-{}".format(policy[key]['srcintf'], policy[key]['dstintf']
default_policy[my_key]['position'] = position
default_policy[my_key]['id'] = key
...
```

2016-11-24 11:37 UTC, mirceaulinic commented
@awlx I have never used Fortinet, but looking at the config, my understanding is that we could use ```uuid``` as a replacement for policy name. Can you confirm it is unique as the name would suggest?

2016-11-24 11:41 UTC, mirceaulinic requested changes
In addition to what David asked, I have suggested few more small changes for more readable code.

2016-11-24 11:41 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            if 'status' in  policy[key]:
You could:

```python
enabled = 'status' in policy[key]
```

2016-11-24 11:41 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            if 'logtraffic' in  policy[key]:
Similarly here:

```python
logtraffic = policy[key]['logtraffic'] if if 'logtraffic' in  policy[key] else False
```

2016-11-24 11:41 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            if 'action' in policy[key]:
And again:

```python
action = 'permit' if 'action' in policy[key] else 'reject'
```

2016-11-24 11:41 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            policy_data = re.sub("\s+", " ", line).lstrip()
I don't understand this line. What's the point?

2016-11-24 11:41 UTC, dbarrosop commented
@mirceaulinic The uuid is unique per ACE so you have multiple on the same ACL.

2016-11-24 11:49 UTC, awlx commented on napalm_fortios/fortios.py
> +            policy_data = re.sub("\s+", " ", line).lstrip()
I strip the leading white spaces.

2016-11-24 11:49 UTC, awlx commented on napalm_fortios/fortios.py
> +            if 'status' in  policy[key]:
The whole key does not exist when the policy is disabled. That's why I only can check if the key is there.

2016-11-24 11:49 UTC, awlx commented on napalm_fortios/fortios.py
> +            if 'logtraffic' in  policy[key]:
Same here.

2016-11-24 12:10 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            if 'status' in  policy[key]:
What I proposed does the same thing, but more readable.

2016-11-24 12:11 UTC, mirceaulinic commented on napalm_fortios/fortios.py
> +            policy_data = re.sub("\s+", " ", line).lstrip()
For this purpose, there's no point in using regex. You can use: ``` line.strip()```.

2016-11-25 11:38 UTC, dbarrosop commented
Ok, I think this is good to go, let's wait and see if @mirceaulinic confirms his suggestions are addressed and/or if someone else has some comment but I think this is almost ready to go : )

2016-11-25 11:41 UTC, mirceaulinic commented
Oh, yes! Sorry, forgot to reply on this. Looks good to me - we only need to release napalm-base 0.20.0 and re-run the tests before merging.

2016-11-25 11:41 UTC, mirceaulinic approved these changes

2016-11-25 11:56 UTC, mirceaulinic commented
@awlx have you run the tests locally for this method, using the napalm-base code from https://github.com/napalm-automation/napalm-base/pull/136?

2016-11-25 11:57 UTC, awlx commented
Yes :).

```
bash-3.2$ nosetests --with-coverage --cover-package napalm_fortios -v TestFortiOSDriver:TestGetterFortiOSDriver.test_get_firewall_policies
test_get_firewall_policies (TestFortiOSDriver.TestGetterFortiOSDriver) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK

2016-11-25 11:58 UTC, mirceaulinic commented
@awlx Thanks!

2016-11-29 08:14 UTC, dbarrosop commented
@awlx can you rebase? There are some conflicts after another PR that has just been merged.

Thx!

2016-11-29 08:38 UTC, dbarrosop commented
As discussed on slack, let's close this one and open a new PR from a new branch : )

2016-11-29 08:38 UTC, closed without merging